/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:66f655ef-def2-4d6f-b09d-5eebfdf551a5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_p1UBqJGQO",
    "aws_user_pools_web_client_id": "34h3p085vtcjf2j36mmck4op3k",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vhidu6doc5b5rcwz7em444ccha.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fb7vormvcvf4xbs2d2rvha25fm",
    "aws_user_files_s3_bucket": "amplifyapp185058-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
